### ISSUE TITLE
Create and add a "Sick Child" form to the child profile

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-chw#1115]
Original implementation issue from LMH is [here](https://github.com/OpenSRP/opensrp-client-chw/issues/1094).

- [x] Create a Sick Child form - from the Child profile view. See overall workflow below.

![Child file](https://user-images.githubusercontent.com/58034047/73659370-299f2600-46a7-11ea-934c-d447d1e488a0.png)

- [x] The form should only be accessible to children who are 2 months or older.
- [x] Title of the form should be **SICK CHILD**
- [x] The CHW will be able to view a history of past filled-out child sick forms accessible from the profile page (read-only). 
-- [ ] In reverse-chronological order.
-- [ ] The date of the most recent visit is referenced in the row.
- [x] The back arrow (or tapping the device back button) takes the user back to the screen they were on before opening the form (Child profile).
- [x] Make sure all the required fields in the [data dictionary](https://docs.google.com/spreadsheets/d/1PueqNJWJQ2_FQ64EcFsEZe-CeHNJGW3KY9EjARoftQQ/edit#gid=0) are filled. 
- [x] Icon to use for the new sick child visit row: 

![image](https://user-images.githubusercontent.com/3488986/75136307-55855880-56f5-11ea-936b-941ccc9578c7.png)

**Comment by rowo** [comment]
@AnnieMungai not sure what this is for but the LMH solution wasn't really meant to be final, just something to do in the 2 weeks we had for LMH work

**Comment by AnnieMungai** [comment]
@rowo this is for BA and Wcaro. There was some discussions around this and we agreed to go with how the Sick child form from LMH had been designed.

**Comment by cafootitt** [comment]
@AnnieMungai Can you find an open 30 minute slot in the calendar this week for me, you, Roger, and Megan to chat about this? Roger is saying that what we did for LMH was due to the rushed timelines and may not be the best user workflow for us to create.

**Comment by rowo** [comment]
@cafootitt can you share requirements documentation and other options you thought about?

**Comment by cafootitt** [comment]
@rowo Since this request came yesterday, we haven't had the time to properly meet your request. We can talk about the wcaro workflow (previously discussed and shared with you) during the meeting. Let's please still have the meeting today, as Allan on our team has already started work on this module.

**Comment by cafootitt** [comment]
Notes from 21 Feb 2020 call:
Roger, Carolyn, Anne, Megan

- Roger shared some feedback from Liberia that points to the need to better link the sick child form to the actual child home visit form/task list (but still keep it available for passive case finding in the child profile dropdown menu)
- Follow-up is needed with UNICEF to talk about how this would make the obs & illness task slightly redundant. Should this be repurposed into strictly historical sick child event(s) only?
- Also work on the design for the follow-up (even though we do not have specifics on the follow-up visit yet, such as number of days, follow-up form, etc.)
-- This entails showing the follow-up visit is due on the child profile, on the main register list page.
- We decided to persist the sick child row in the child profile (in LMH it disappears after the current sickness episode is marked as resolved). The historical sick child forms would be listed in reverse chronological order.

Action items:
- Roger to let the team know when he'll provide updated mockups
- Carolyn to follow-up with UNICEF as per above notes
- Anne to update the IMCI github issue with any changes as per above

**Comment by rowo** [comment]
My understanding is also we're not actually changing button placement now, so designs are not urgent. I need more information on whether we are doing either follow up or an idea of "currently sick" which are different things that aren't being done now.

**Comment by cafootitt** [comment]
@rowo Ok, I misunderstood the urgency then. I thought the urgency came from you, because we were implementing this for wcaro/ba now and you alerted that they weren't final designs and needed to be discussed.

And yes, we need designs for the follow-up and currently sick, but they are not being implemented in this first version of IMCI for wcaro and ba.

**Comment by rowo** [comment]
@cafootitt The urgency was for this discussion itself to happen. In the action points, it says I should be providing updated mockups... I was saying designs are actually not urgent since the outcome of the discussion was there was no time to change anything, so it's the same time problem as LMH except it's not for testing only. I would still not consider these final designs that have been thought through enough and recommend that we try to talk about this type of stuff sooner next time. cc: @msschroeder 

I can work on new designs, but don't think they are urgent because they are for a future release without clear requirements or client buy-in. Unless the release is a few weeks after the first version... in that case we should get started now.

**Comment by allan-allay** [comment]
IMCI first-round QA suggested fixes from @AnnieMungai 
[IMCI QA.docx](https://github.com/OpenSRP/opensrp-client-chw/files/4322981/IMCI.QA.docx)

**Comment by cafootitt** [comment]
Closing, too outdated. Client unsure which direction we're proceeding now with IMCI, pending further discussions.
