### ISSUE TITLE
[Discussion] Do we have a better "toaster message" for headings?

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#1185]
The "Anaemia Treatment" blue toaster message here is bothering me a bit. The way we have it in the form is that it's supposed to be a heading, representing a new sub-section of that page (i.e. all pages are generally broken down into the signs/symptoms, diagnosis, and treatment sections. I'm realizing now that this doesn't lend itself very well to the design of our native forms. If we don't have a different type of toaster message (i.e. one with a neutral color, no check mark, no info icon), then my feeling is that we should remove this.

@rowo Do you have any input on this?

![Screenshot_20200323-161419_CFC-RTM_-_Togo__1_](https://user-images.githubusercontent.com/3488986/77340546-5e357280-6d25-11ea-9853-ce8c3656838e.jpg)

**Comment by rowo** [comment]
@cafootitt this came up in the forms initially done for LMH as well and caused a lot of confusion all around. We never got to addressing it (the client opted to remove the forms rather than try to fix the issues with the time we had), but the recommendation was to break these types of things into multiple pages (LMH's sick child was more of an overall symptoms, diagnosis, and treatment vs. what you have here which is individual sections of symptoms, diagnosis, and treatment.):

<img width="629" alt="Screen Shot 2020-04-02 at 12 26 43 AM" src="https://user-images.githubusercontent.com/1584163/78210594-a583d780-7478-11ea-82d9-0cc64e97c272.png">

The reason we didn't go with the new styling also was there wasn't a lot of time and fine tuning a new styling like this could take a while. I think it would be nice if we did have a group header -type style that we could use at some point with our native forms since that would be useful. 

But in this case, it does seem like you can remove it. I don't even think the header is necessary even if the styling was more appropriate since treatment is only one question. 

Side note: this isn't a toaster message. I would call this an "in-line message" or "in-line notification". Toast indicates something that pops up then disappears, like a slice of toast.
