### ISSUE TITLE
Send information to RapidPro causing the mother and father to go through a specific flow

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#1192]
When a child registration form is filled:
- [x] The form values sent would have to have child's caregiver base-entity-id and phone_number and head of family's base-entity and phone number and will trigger a flow `Child registration- Flow ID: f54ab583-af3a-4736-b3d3-8ba45b438f9b` to begin
- [x] The form would also need to send the child's `first_name`, `surname`, and `dob`

**Comment by manutarus** [comment]
@msschroeder is this only for child registration or we will need to do this for children added through the pregnancy outcome as well, if so how do we want to handle this for multiple babies?

**Comment by msschroeder** [comment]
@manutarus This will be for the child registration and the pregnancy outcome form. I separated them into separate issues.

**Comment by HusnaHariz** [comment]
The following payload is posted to the flow
```
{
    "flow": "child_registration_flow_uuid",
    "contacts": ["rapidpro_contact_uuid"],
    "extra": {"child_name": "name", 
              "child_dob": "dob", 
              "child_age": "age", 
              "child_base_entity_id": "baseEntityId",
              "child_number": "(number of children mother has) +1",
              "family_head_base_entity_id": "family_head_base_entity_id",
              "family_head_phone_number": "phone_number"
             }
}
```
The primary_caregivers number is not passed since this can be obtained from the contact's rapidpro variable (@contact.urn.tel)

The `family_head_base_entity_id` is always passed, but the phone number is only passed if this individual has their own unique rapidpro contact. The reason I didn't pass the phone number is because this number is possibly shared with the primary_caregiver. So you'd inadvertently be triggering the secondary flow against the wrong individual. 
The `family_head_base_entity_id` also technically doesn't need to be passed because we can retrieve it from the contacts `head_household` field.

To use the variables in the `extra` field within the rapidpro flows use the `@trigger` variable. For example to reference `child_age`, use `@trigger.params.child_age`. You'd need to manually specify the specific field name.
