### ISSUE TITLE
Cannot add users as new team members

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#1275]
### Issue
There are certain users I cannot add to OpenMRS as a new team member. When you have the developer tools open in the browser an error pops up and the user is never created a new team member.

### To replicate
1. Please try and create a new team member with the following user JENIVA JAMES KOKUTONA 
2. I will share the information on Slack channel
3. Ensure you have the developer tools open in the browser
4. An error will occur and the user is never created as a new team member

**Comment by allan-allay** [comment]
After taking a look at this with @dubdabasoduba  we saw the **Existing Person** search returns the details of the user but in addition it does return some `null` values.
The failure happens when going through the results to get the person's ID (UUID for a person whose name is selected)
A faster fix is to remove the nulls from the result set then test. 
This is to be done in the `TeamManagement` Module

**Comment by allan-allay** [comment]
We couldn't determine why this happens with the specific user, so we'll try recreate this on the Staging server

**Comment by allan-allay** [comment]
This https://github.com/OpenSRP/openmrs-module-team/pull/49 should resolve the error identified
