### ISSUE TITLE
Change all "provided" to "given"

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-chw#144]
I think we've been inconsistent in the mockups between using provided vs. given, and I'm noticing now that both are used in the child services, which is a bit confusing. I think we should consistently use "given" instead of "provided" as that's a little more user-friendly to the CHW.

Low priority.

**Comment by ladleo** [comment]
I cant seem to find the word "provided" in any of the child services.

**Comment by msschroeder** [comment]
@ladleo This issue is related to the child home visit form. On the first screen of the child visit, there are different services:
![Screenshot_20190319-114203](https://user-images.githubusercontent.com/20777928/54592194-ee6b1880-4a3c-11e9-9876-718983af63f1.png)

In the sections MNP, Vitamin A, and Deworming, you will see the question uses "given"
![Provided_2_1](https://user-images.githubusercontent.com/20777928/54592205-f4f99000-4a3c-11e9-9c1d-32813e821582.jpg) ![provided_2](https://user-images.githubusercontent.com/20777928/54592208-f5922680-4a3c-11e9-9796-0bd3a6b8212f.jpg)

Once any of the services have data entered, the text below the service no says ".... provided .....". For example, when I select MNP 1st Pack and enter data, the subtext below MNP 1st Pack now reads, "Provided on 19 March 2019"
![provided_3](https://user-images.githubusercontent.com/20777928/54592221-fcb93480-4a3c-11e9-8ac3-71e480eed520.jpg)

We want to make sure that it is consistently given and not provided. Please let me know if you need further clarification.

**Comment by cagulas** [comment]
Lgtm
