### ISSUE TITLE
OPV0 and BCG fields in Pregnancy Outcome form not accepting any dates; need to check validation rules

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#1712]
In the Pregnancy Outcome form, the OPV 0 and BCG fields are not accepting any dates.
The constraint should be `>= {delivery_date} and <= {today}`, but if you enter a delivery date of Feb 19, and try to enter Feb 22 (today's date) as the date, it is not accepted. Similarly, if you enter the delivery date, Feb 19, that is not accepted either.

![Screenshot_20210222-133832_CFC-RTM - RDC](https://user-images.githubusercontent.com/3488986/108717000-c6b74180-74ea-11eb-85a0-75f5498cb187.jpg)

**Comment by qaziabubakar-vd** [comment]
- Problem occurring because of the date format used in client-chw Project
- We are using date-format `dd MMM yyyy` as a global configuration
- On native forms level, the `GreaterThanEqualToComparison` class uses the datepicker's default format of `dd-MM-yyyy`
- Having different formats in native forms repo and the project gives rise to a runtime exception

Possible Solution:
- Modify the `DatePickerFactory` in native forms repo to override default date format
- Modify the comparator classes to work with any date format that is being used by the DatePicker widget

**Comment by cafootitt** [comment]
New version of native form repo released today. Expecting to close issue by EOD today.

**Comment by cafootitt** [comment]
V1.1.4 Togo version build date 10 march 2021 - lgtm
