### ISSUE TITLE
[Discussion] New requirement about showing location filter for CHSS role

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#181]
This is a new requirement that came up during the p2p sync discussion that was previously unknown.

The scenario (as is):

- CHA registers a child (or anybody else in the app)
- The data is synced to the CHSS worker according to the location syncing permissions
- If the CHSS edits a record that was previously created by the CHA worker, the location ID for that edited record will be the CHSS's location, not the CHA. This is a problem, because the CHA will not be able to sync the updates back to the CHA worker.

What we discussed doing is adding a location view filter in the CHSS app whereby they can only view records for the specific location they have selected in the location filter. By having this location selected, any edits they make to records will then be assigned that location ID.

For eg:

- CHSS 1 has CHA 1 and CHA 2 workers underneath her whom she supervises.
- CHSS 1 logs in and has a location filter in her app whereby she can only view CHSS 1, CHA 1, or CHA 2 location at a single time. She will not be able to view a list of all records across all her CHAs in a single screen. I think this is fine.
- If she happens to edit any record, since the appropriate location filter is already selected (she can't view the record otherwise); it will automatically assign the correct location for her edit.

Things we need to discuss:
- My understanding is we can still create a single apk for both CHA and CHSS, and the CHSS would view this location filter because of her role. This needs to be confirmed, as we want to avoid the situation where we have to do two different apps. **CG: Eph please confirm this**
- What happens if the CHSS uses the search bar to retrieve a record from a different location from what she has currently selected in the location filter? **CG: Not discussed yet**
- What UI elements are required to implement this change? **CG: If we implement something similar to ZEIR location dropdown, this is easier to implement. Or even what we have now in ANC in the Me menu**
- What's the LOE required for this? This will probably need to be worked on in tandem with the p2p sync feature. **CG: From Eph - 3-5 days, depending on the design**

**Comment by keymane** [comment]
Yes, it's possible to differentiate CHA from CHSS using the location tags.

**Comment by rowo** [comment]
Notes:
- CHSS 1, CHA 1 and CHA 2 would all have unique client/record lists that do not overlap
- The main job of a CHSS user is a one-on-one review meeting
- The above implies that frequent switching and needing to see which location they are in is not necessary, though it should be semi-accessible. They might have to switch in an out if they forget which list a client is in.
- CHSS will know which list a person is in or will use a CHA as starting point during review.

**Comment by rowo** [comment]
I can think of 4 existing UI patterns that do similar things to this issue:
- A) ZEIR-style location selector in the top - This is register specific I think, though doesn't have to be.
- B) [ANC me](https://github.com/OpenSRP/opensrp-client-anc/issues/58) - The CHW app for WCARO and BA don't have Me menus because the hamburger menu was added to deal with all of the registers.

For the next Reveal app, there are two other interactions:
- C) [Operational area selector](https://marvelapp.com/6b2b86b/screen/53331759/layer/82334278) in the hamburger menu. This is pretty much the same as the ANC style location selector
- D) In the [same menu](https://marvelapp.com/6b2b86b/screen/53026110/layer/82334124), there is a similar "switch campaign" button. This is different from a pull down/dialog in that the app actually starts up on a [list of campaigns](https://marvelapp.com/6b2b86b/screen/53420602) (the equivalent of a CHW register). This is the only one that avoids going straight to a previously viewed or a default register, which seems idea for this use case. This is similar to the step in ANC that was suggested around creating an initial fork for the user about whether they are registering someone new or looking someone up.

I think pattern D works well for this. If it's just about reviewing during one-on-one meetings (or to review individual performance), the first step would always be to select the list you want to see. It's similar to C (which is in itself similar to B), with the main difference being you don't go straight to a register list.

**Comment by cagulas** [comment]
@rowo thanks for your input.

@keymane Can you look at option D and see if this is feasible from an implementation resourcing standpoint. Keeping in mind we want to make sure we don't have separate apks for CHA vs. CHSS worker.

**Comment by cagulas** [comment]
@keymane What is the allowed edit period that you're working on now? I think it's 24 hours after home visit is submitted, right?

**Comment by cafootitt** [comment]
Closing this, too outdated.
