### ISSUE TITLE
[Discussion] Change home visit reset to 12 hours instead of 24 hours

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#190]
Placeholder issue for the discussion of whether we change the home visit reset to 12 hours instead of 24 hours. We can maybe raise this on the call tomorrow with the client.

**Comment by cagulas** [comment]
@mberg On this one, I was just chatting with our team, and I would propose that we leave it to be 24 hours reset, because this is also the time window for making edits to the home visit as well. 12 hours might be too short of a window to make edits, because if they review their home visits the next day, they already wouldn't be able to make any edits if it reset after only 12 hours. What do you think?

In future, we'll probably want to discuss the functionality of allowing edits even after 24 hours, but this isn't something we currently support.
