### ISSUE TITLE
CRVS: Change Requests/QA Feedback Issues

### ISSUE THREAD

**Issue by ageryck** [opensrp/opensrp-client-chw#1983]
This will be a holder issue for bug reproduced and suggested changes, each task resolved or assigned to an engineer will be marked as done;

- [x] Change nationality spinner to a text box in Family member registration, out_of_area_death_form, family_details_remove_member and family_register

- [x] update status in death summary; form to ask all questions asked in remove family member form. Currently ask partial question but only if death certificate is YES. Manner of death is asked as an open text rather than drop down spinner options.
- [x] Remove family member for under 5 should ask all question in remove family member form
- [x] Edit/Update Death certification; form not loading back saved records
- [x] Out of Area Death; MCCD follow on questions [relevance](https://docs.google.com/spreadsheets/d/138JD_Zn3xTSsACn5cq8ZlGyeC8BEzmiU0XDKm1_Moeg/edit#gid=1225359750) not implemented 
- [ ]

**Comment by joyce-x-chen** [comment]
**NOTES**
@ageryck The `Remove Member Form (Died)` tab in the [data dictionary](https://docs.google.com/spreadsheets/d/138JD_Zn3xTSsACn5cq8ZlGyeC8BEzmiU0XDKm1_Moeg/edit#gid=1334292400) was locked so I created a duplicate called `Copy of Remove Member Form (Died)` tab and suggested edits with red text.

**GENERAL FEEDBACK FOR CLEANING UP THE DATA DICTIONARY**
- [ ] Relevance and select one options should be specified in the relevant columns in the data dictionary, not written in the label columns and displayed to the CHW. Can we please clean this up? For example
[ ] We don't need to display "(Y/N)" to the CHW. "Yes" and "No" will appear in the drop down list
[ ] We don't need to display "(if death notification done)" to the CHW. We should just note the relevance {death notification}="Yes" for programming the workflow
- [ ] Please double check that the question phrasing, order, and options are consistent between the `Remove Member` and `Out of Area Death` forms. I found some inconsistencies. 
- [ ] The `Add Child Under N - Out of Area` tab looks incomplete and does not have the birth certification questions. 
- [ ] Could we update the tabs to match the menu in the app itself for consistency and avoid confusion? 

**SPECIFIC FEEDBACK FOR DEATH REPORTING**
- [ ] If a family only has one member, I am not able to report the death of the family member if I'm in the individual's profile. I can remove the entire family if I'm in the family profile, but I cannot remove the entire family if I click to remove the individual from their individual profile. Steps for replication:

1. Using demo4/Amani124
2. Select Esco family, which only has one Male 63-year-old family member - Julian Esco
3. Select Julian Esco, 63
4. Click 3 dots in upper right-hand corner and select "Remove this person"
5. Here, an error message pops up stating "Before you remove this member you must select a new family head." However, since this person lives alone this is not possible and you cannot report his death.

Preferably, if a family only has one person, the error message would state: "This family only has one member. Please confirm if you would like to remove the entire family." Then a button that takes you to "Remove family" page.

- [ ] @ageryck mentioned that the `Remove family member` and `Remove child under 5` forms should assume that the reason for removal is Death. Therefore, the "Reason" field can be removed entirely. If this is the case, please ignore the next comment.

- [ ] `Remove family member` form should not display the question "Was the deceased admitted to a health facility in the past 4 weeks?" and "Do you know the cause of death?" unless the "Reason" for removing the family member is "Died." 

- [ ] The `Remove family` form currently only gives 2 options: "Moved away" and "Other." This form should look the same as the `Remove family member` form. 

- [ ] `Remove child under 5` form should look the same as `Remove family member` form EXCEPT: 
[ ] Do not display "Marital status" question in 'Remove child under 5' form
[ ] Addition of "Was this a stillborn death?" if the deceased was <27 days old. 

- [ ] Please change phasing of the question "Was MCCD conducted?" to "Was a medical certificate of cause of death (MCCD) issued?"

- [ ] In the data dictionary, "Do you know the cause of death?" is only relevant if the "place of occurrence of death" is the health facility. Is that accurate or should this be asked regardless of location? 

- [ ] Instead of writing "Death certificate issuance date (if certificate received)" and "Death certificate number (if certificate received)", we should make those two questions relevant only if the answer to "Does the family of the decedent have a death certificate?" "Yes". @ageryck The `Remove Member Form (Died)` tab was locked so I created a duplicate called `Copy of Remove Member Form (Died)` tab and made edits with red text.

- [ ] The notes in rows 64 and 65 of the `Remove Family Member (Died)` tab and rows 77 and 78 of the `Record Death Form - Out of Area (New)` tab do not make sense. They say:
[ ] "Ask to see the death notification and instruct the family member to register the death at CRO. (if death notification done)" If death notification was already done, why would they need to register the death at the CRO again? 
[ ] "Instruct the family member to have the death registered at CRO. (if **_birth_** notification not done)" I think the parentheses should say "If **_death_** notification not done." 
[ ] The notes are also not displayed in the forms. I don't know if this is intentional or an oversight

- [ ] The pregnancy questions are not displaying even when removing family members that are women of reproductive age. There are two questions: 
[ ] "Was the deceased pregnant?"
[ ] "Did the pregnancy contribute to her death?"

- [ ] The relevance for "Do you know the cause of death?" was different in the `Remove Member Form` tab and `Record Death Form - Out of Area (New)` tab. Based on this [workflow diagram](https://docs.google.com/presentation/d/1EXy3-dVbcXjFv5JpTzixSGlKTMoKVE0m/edit#slide=id.p1), I updated the `Remove Member Form` sheet to "{medically_treated} = "Yes". 

- [ ] Change text "Removing entire family" to "Remove entire family." I don't know where in the data dictionary to specify this. 

- [ ] Ager should the `Out of area death` page and `Death certification` page look the same? 
[ ] Is there any reason it says "update status" on the `Death certificate` page vs "update details" on the `Out of area death` page? I think consistency helps to avoid confusion for CHWs. 
[ ] I don't see "Certificate received" and "Certificate not received" statuses displaying in the `Out of area death` page. Steps to replicate:
1. Using demo4/Amani124
2. Test Six death certificate details updated but the status is not changing to "Certificate received." 

**SPECIFIC FEEDBACK FOR BIRTH REPORTING**
- [ ] When I update the status of a child in the `Birth Certification` page, the data does not appear to save. Steps to replicate:
1. Using demo4/Amani124
2. Go to `Birth Certification` page
2. Press "update status" for child Angela Cavuto, 6m
3. Answer "Yes" to "Does the child have a birth certificate?"
4. Enter 5 Feb 2022 for "Birth certificate issuance date"
5. Enter 123qwe for "Birth certificate number" 
6. Select "Mother only" for informant
7. Press "Save"
8. I am re-directed to the `All Families` page and when I go back to `Birth Certification` page, the information I entered for Angela Cavuto is unsaved and her status is not updated.

- [ ] The notes (e.g. rows 16 and 17 in the `Birth Certificate Form`) are not appearing

- [ ] The out of area birth form should include all questions in the `Birth Certificate Form` tab. 

- [ ] Birth certification does not display "Certificate received" and "Certificate not received" statuses.

**Comment by joyce-x-chen** [comment]
Please remove the Liberia logo from the CRVS login page.

**Comment by ageryck** [comment]
> Please remove the Liberia logo from the CRVS login page.

We will replace this with DRC logo for the current CFC App, client did not share any specific app branding

**Comment by rowo** [comment]
@ageryck @joyce-x-chen just reviewed the app from https://onaio.slack.com/archives/C01KKF9LUR1/p1643981557660599 and read the thread above (tried not to reproduce the known issues).

1. We definitely cannot assume reason for removal is always death — if only to account for user error.
2. The relevancy logic is not working in the "remove family member (over 5)" form. Nothing should appear before a reason for removal is selected as defined in the "Relevance" column. I'm sure this was mentioned and i missed it.. It works for under 5.
3. Re: the above comment, `The Remove family form currently only gives 2 options: "Moved away" and "Other." This form should look the same as the Remove family member form.` The "Remove family" and "Remove family member" forms cannot be the same since the fields aren't the same and we don't really want the remove family to be like a bulk death reporting form either. The workflow for removing the last remaining person would probably be doing the "remove family member form" with a confirmation in step one that you are removing the last person, which will delete the family/structure as well.

**Comment by joyce-x-chen** [comment]
@rowo good point about not using `remove entire family` to register the death of a person who lives alone. I proposed that as a workaround to the logic that prevents one from using the `remove family member` without re-assigning head of household. In this case, we cannot register the death of an individual who lives alone. Is it necessary to keep the logic that prevents the removal of a family member without re-assigning head of household? cc: @ageryck

**Comment by joyce-x-chen** [comment]
@ageryck Leigh and I have noticed while testing the CRVS app that we periodically get logged out of the app and receive the following error message: “you have been logged off as your account has been disabled.” In this [Slack thread](https://onaio.slack.com/archives/C018U26P3RU/p1644308625632869), we received a few suggestions: 

- [ ] Increase the time before a user is automatically logged out, and it should be following a period of **_inactivity_**. 
- [ ] Display a different error message such as "You have been logged out due to inactivity. Please log in again." 

This is a nice to have - if there isn't time to squeeze this in, that's ok.

**Comment by ageryck** [comment]
> @rowo good point about not using `remove entire family` to register the death of a person who lives alone. I proposed that as a workaround to the logic that prevents one from using the `remove family member` without re-assigning head of household. In this case, we cannot register the death of an individual who lives alone. Is it necessary to keep the logic that prevents the removal of a family member without re-assigning head of household? cc: @ageryck

looking into this

**Comment by ageryck** [comment]
> @ageryck Leigh and I have noticed while testing the CRVS app that we periodically get logged out of the app and receive the following error message: “you have been logged off as your account has been disabled.” In this [Slack thread](https://onaio.slack.com/archives/C018U26P3RU/p1644308625632869), we received a few suggestions:
> 
> * [ ]  Increase the time before a user is automatically logged out, and it should be following a period of **_inactivity_**.
> * [ ]  Display a different error message such as "You have been logged out due to inactivity. Please log in again."
> 
> This is a nice to have - if there isn't time to squeeze this in, that's ok.

@allan-on will be looking on this logged under this [issue](https://github.com/opensrp/opensrp-client-chw/issues/1993)

**Comment by ageryck** [comment]
majority of listed issues have been translated into tshirt size issue and already handled pending QA on the project [board](https://github.com/orgs/opensrp/projects/53), closing this while parking the entire family removal issue for future handling

**Comment by charlene-570** [comment]
From @joyce-x-chen  comment issues mentioned here are the bug reports:


Relevance and select one options should be specified in the relevant columns in the data dictionary, not written in the label columns and displayed to the CHW. Can we please clean this up? For example
             [ ] We don't need to display "(Y/N)" to the CHW. "Yes" and "No" will appear in the drop down list
QA Results
Actual Results: 
"(Y/N)"  is still displayed see screenshot below
![Screenshot_20220210-171404](https://user-images.githubusercontent.com/85434942/153598466-576cc635-2ad6-4119-b4f0-d9204edc1685.png)

Expected Results:
"(Y/N)"  should not be displayed

**Comment by charlene-570** [comment]
Logo has been changed From Liberia to “Justice Paix Travail” See screenshot below
![Uploading Screenshot_20220214-141410.png…]()

**Comment by charlene-570** [comment]
@ageryck Report on the following : The Relationship descendant drop down Sibling is shown twice see screenshot below
![Screenshot_20220215-142818](https://user-images.githubusercontent.com/85434942/154081305-b9fcda30-c5aa-4306-9543-5e15821ecc8c.png)
Steps to reproduce 
1.Login 
2.Click menu
3.Click Death Certificate
4.Click on update status
5.Select Relationship to decedent
