### ISSUE TITLE
Change phone number to optional

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-chw#207]
Users are saying that not all families will have access to a phone, so phone number cannot be required.

In add family head, add family member forms, we need to make phone_number optional. Also, when trying to change family head or change primary caregiver, we also need to make the phone number optional there as well.

The team understands that this could potentially mean no phone number for the family at all and this screen would be empty:

![screenshot_20190307-212433](https://user-images.githubusercontent.com/3488986/53979722-96204680-411f-11e9-81d1-13a81118892e.png)

@rowo I was thinking in place of Call [number], we could insert "No contact number provided". What do you think?

**Comment by rowo** [comment]
@cagulas I'd almost say we don't let the user reach this dialog because it's kind of disappointing and you have to wait until you know if there's a number or not until after the dialog comes up. 

Because of how the forms are set up, I'm assuming we can't replace the Call button with a form to add a number for the family caregiver. 

So we could either disable that call button (with or without explanation) or just remove it from the options. I like disabling.

![screen shot 2019-03-07 at 2 19 04 pm](https://user-images.githubusercontent.com/1584163/53982899-090bcc00-40e4-11e9-86a8-479a15afa930.png)

**Comment by cagulas** [comment]
I like the disabling too (middle one).

@keymane Please say if this is unreasonable to implement because of any complexities.

**Comment by rkodev** [comment]
@cagulas the second option looks great. Its achievable to
