### ISSUE TITLE
WCARO DRC: App Issues

### ISSUE THREAD

**Issue by ageryck** [OpenSRP/opensrp-client-chw#2105]
The client reported the following bugs, we need to reproduce them and if confirmed resource them to OpenSRP support for fixes;
- [ ] Women that have delivered are not updated, after delivery still marked pregnant
- [ ] Children that are 5 years are still in the child clients register
- [ ] Cannot register people older than 45 years to the family register

Expected Outcomes;

- women delivered through a pregnancy outcome form should move out of ANC register and their pregnant status ceases
- children above 5 years should be checked out of the child register
- family member should allow registration of any age

**Comment by Mstjamush** [comment]
I've tested the .apk in the store and cannot replicate these bugs

- [x]  Women that have delivered are not updated, after delivery still marked pregnant -  _managed to get a woma from ANC to PNC by registering a 'Live Birth'_
- [x]  Children that are 5 years are still in the child clients register -  _changed the device date to 2024, so that children that are 3 yrs plus maybe more than 5 yrs, and they were no longer in the child register_
- [x]  Cannot register people older than 45 years to the family register - _registered a family member who's 54yrs old_

**Comment by ageryck** [comment]
Thanks @Mstjamush this is noted
