### ISSUE TITLE
WCARO DRC: New Users setup

### ISSUE THREAD

**Issue by ageryck** [OpenSRP/opensrp-client-chw#2106]
Background: The client has requested support to set up a [list ](https://docs.google.com/spreadsheets/d/1hyKXS7ezhywVs5TLvEQL_B7H1xn2igZV/edit#gid=1683708961)of new users from three regions namely; BUMA, KINDO & DINGI-DINGI
Below are suggested action items:
- [x] Ask the client to share the list of users in the predefined template for new users, locations and teams
- [x] Induct client on how to use [OpenSRP Web](https://web.wcaro-cd.smartregister.org/) for them to do this by themselves
- [ ] Create new users on behalf of the client and conduct training later

**Comment by joyce-x-chen** [comment]
Hi @hilpitome - thanks again for the meeting yesterday. Is it possible to export a csv with the location hierarchy and list of locations pre-populated from OpenSRP Web? I think that would save the client time and also mitigate risks of conflicting information.

**Comment by dubdabasoduba** [comment]
@joyce-x-chen We do not have the export functionality on OpenSRP web/server. 

@hilpitome maybe we can use [this tool](https://github.com/opensrp/opensrp-data-import) to import and create new locations, users, and practitioners from a CSV. 

Someone will however need to do the assignments manually. 

@joyce-x-chen @ageryck Clients are advised to manage the user assignment pieces on their own after training on how to use OpenSRP web. Based on this I would advise going with option 2.

**Comment by joyce-x-chen** [comment]
@dubdabasoduba isn't the import tool also able to assign users to teams, and by proxy, to locations? 

That is the more time-consuming and error-prone part of creating these user accounts.

**Comment by dubdabasoduba** [comment]
@joyce-x-chen no it's not. For the tool to perform the assignments, it needs to know the exact users to assign to a team and the correct teams to assign to a certain location. 

This is a bit complicated to build and correctly track when doing automated imports. This is the reason it was left out.  

Maybe we can revisit the feature added targeting the FHIR-based implementation.

**Comment by joyce-x-chen** [comment]
Ok, thanks for the clarification @dubdabasoduba. Yes, I think this will be a needed feature for FHIR Web.

@ageryck I agree with Ben that it would have been better to have them do the user account creation themselves rather than wait all these days when we haven't been able to move it forward. I'll do the following as a next step:
- ask them to share the account information in the required format 
- clarify that we will only be able to import the user accounts but that they will need to do the team and location assignments themselves
- suggest that it may be faster for them to do the user account creation themselves 

Can you please pick this up on Friday once you're done with the workshop? Thanks everyone.

**Comment by ageryck** [comment]
the client wasn't capacity built because of language barrier challenges. DRC has since terminated this contract
