### ISSUE TITLE
Update child's profile when they turn 5 yo

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-chw#250]
When a child turns 5 yo, they are removed from the child register, and they also remain a family member listed in the family members page. We need to update the 5 yo's child profile page, however, because it still shows that home visits are due and upcoming services are scheduled. Once a child turns 5 yo, they are not eligible for any services in the app anymore, so we should not show home visit or upcoming services. The medical history page would be helpful to show still, and I imagine this is ok to do, since it's already there. See below my proposed changes:

![Screenshot_20200321-102833](https://user-images.githubusercontent.com/3488986/54808082-28802880-4c90-11e9-9900-c0914fed4aaf.jpg)

@rowo Pls add your feedback and/or changes directly and then un-assign.

**Comment by rowo** [comment]
@cagulas 
I imagine the profile would just change to a regular household member profile like in https://github.com/OpenSRP/opensrp-client-chw/issues/48 so this seems to nearly cover it.

One change we can discuss: we had a conversation in Slack for BA that the medical history would appear like anybody else in the current condition/register and not show any previous historical information (so here, as if a 5 year old were newly registered). We could do it differently here, but to simplify the product the medical history should probably get removed.

**Comment by cagulas** [comment]
@rowo Thanks for the input. I think leaving medical history would be best. It's already there, and we don't have to change anything to keep it there. From a user standpoint, that's a history of their work as well, so to a user it might seem like you're "erasing" the work that they did. From a health standpoint, if the child does get sick later, reviewing their medical history and immunization status will be helpful.

**Comment by rowo** [comment]
@cagulas The advantages you've highlighted on leaving history for WCARO are not in dispute and make sense. They all also apply to the BA app i.e. it will seem as if medical history is erased if it is removed and medical history and immunization history would be helpful (although — we've made the decision in WCARO — not so important as to enter after the fact).

I don't think it's clear that "we don't have to change anything to keep it there". So the point that needs to be made is more on why it's important enough that we treat WCARO vs. BA differently. And, to scope the additional work and overhead cost this requires if any.

In WCARO, newly registered over 5's will not have that history so there's some logic to hide that section for them (or to logic not to show if it doesn't exist). For BA, I don't know what the work looks like to treat the child--> household member transition differently from the other transitions.

**Comment by cagulas** [comment]
Just so I understand, once a child turns 5 yo in BA, they are eligible for what? Is it only malaria services, so a child over 5yo would in theory only have malaria history in their medical history?

**Comment by rowo** [comment]
Here is the documentation I've seen so far: https://docs.google.com/presentation/d/1a5-sLnyzBxIAipec1W4W3R5rr-UaPaAXpAoEVgY2t94/edit#slide=id.g5007bd54af_0_37

**Comment by rowo** [comment]
More elaboration... This could be viewed as an amendment of the decision in the BA thread, which basically is "always show the client profile based on what register/medical category they are in" — notwithstanding the known/documented usefulness of past medical history information from health and user perspectives for U5 and beyond.

So here if we want to treat U5 transition to adult differently, where the adult profile is different depending on if they used to be U5 in OpenSRP vs. newly registered, then the main thing to figure out is how much additional work it will be. 

It does feel like a slippery slope from a product perspective since if we're doing this, why shouldn't we treat anc, pnc, fp, sick child, malaria the same b/c that information is useful as well (maybe slightly less so?) and also — why shouldn't we let users enter previous immunization data if they want to for >4 (adults) if it is that important?

**Comment by cagulas** [comment]
Child immunization history is a bit of a unique use case. ANC history, for e.g. is typically captured in the next pregnancy anyway, and ideally, we'd be able to store the ANC history and pre-populate the relevant bits in the current pregnancy record. In other words, ANC history isn't really important until the woman becomes pregnant again. PNC is grouped with ANC and we don't necessarily have to consider them as two separate clients from a medical history-perspective. 

Child is unique, because when they turn 5yo, they are still a child. The 5yo cut-off is a bit arbitrary. They need to age-constrain service delivery for resourcing purposes and how we measure indicators of health for obvious reasons, but a 5yo child is still a child, and their medical history will still be useful for a time. Think also of how children need to show their immunization record for school enrollment, for example. 

Since we are seeing that medical history will continue to show in the 5yo child's profile in the app until we make a change, the change we make would be either removing medical history at 5 years of age or removing it at a later designated age, both of which I would estimate are probably similar LOE. That's why I was proposing leaving medical history as is for now (least amount of effort option) and make a decision on age limit later.

**Comment by rowo** [comment]
Definitely, if we left WCARO as is and medical history just stays on whatever it was last, that's easy. But we cannot do that for BA. The opensrp-client-chw decision is "remove the medical history at age 5 i.e. show history based on client 'status'" — and keeping the product consistent among implementations seems like the least overall effort bc doing it differently either means (1) for each implementation means it's configurable, or (2) we change up the rules only for the U5 with immunization history use case.

**Comment by msschroeder** [comment]
@rowo Is there a reason that we have to remove the medical history at the age of 5 for BA?

In terms of the different options, I would think 1 would be better because out of all the services offered for child health, I would think the immunization rather than other services would be the most useful.

**Comment by rowo** [comment]
@msschroeder I'm not debating it's value. I am the one who brought up the value of showing history beyond current register in a BA comment — though here I'm also the one who is trying to keep scope focused since no one is talking about the cost of the decision.

The reason to not do it is it goes against with I'm assuming is the most basic option at a product (i.e. cross project level), which we decided on in Slack for the BA chw app — just showing the profile of whatever register the person is in. This is a change which will results in an unknown level of added complexity as mentioned above. 

My feedback has been you can't argue for this being a requirement by just saying it's valuable to a user (since that does not take into account project cost or product priority) and that the idea that it's the least effort is a unknown and probably unlikely since it actually adds logic when you look at the CHW app for BA.

**Comment by cagulas** [comment]
I think we might be thinking into this too much. Since medical history for children above 5yo is already there in the CHW app, let's leave it there for now (no cost in this decision) and punt the decision of if and when medical history changes for this client type of children-who-turned-5yo-in-the-app to a later time. 

If it helps, in BA, we can even create a separate medical history page for the 5yo-now-adult (side note: do we know what this looks like yet?) and not touch the U5 child medical history page (yet).

**Comment by rowo** [comment]
The adult profile (defined over 4) is a basic profile without a medical history... same as defined in WCARO

**Comment by cagulas** [comment]
@rowo Cool, so I'm suggesting then that medical history for children who turned 5yo in the app is just left there for the time being, which is a no cost decision. Is everyone ok with this for now?

**Comment by rowo** [comment]
So the decision is: 
- For WCARO, the medical history is left there
- For BA, the medical history is removed

**Comment by cagulas** [comment]
I was actually proposing for both WCARO and BA, the medical history just remains there for now, as this is a no cost decision for both projects.

@msschroeder any issues with this?

**Comment by rowo** [comment]
Sounds like you are saying: For Under5 --> Over4 transition, the medical history remains. For all other transitions, the medical history is replaced with a new status/register medical history that reflects the current state of the client. Is that correct? 

Then (hopefully this doesn't happen for a long time) for Under5 --> Over4 --> ANC --> ? What history is shown for that case?

**Comment by rowo** [comment]
Or are you suggesting that an ANC --> Over4 would also have their history remain?

**Comment by cagulas** [comment]
I'm suggesting just for Under5 to Over4/5 (I think you said BA is 4, while WCARO is 5). 

And yes, hopefully Under5 to Over4/5 to ANC would not happen for a VERY long time. Definitely long enough to have another round of updates on the module where this decision is made :)

**Comment by mlberg** [comment]
For now, I propose the only medical history we keep is Child Immunization after the transition.  This applies to all CHW versions of the app.  From a MVP product standpoint / I realize it adds complexity over just show current status but I think from a health use case we want to keep it. 

To summarize how I propose we move forward:

- We design health profile to show immunization data.  If it exists it displays.   This applies to children over 4 or 5 as they transition.  Health rationale here is when visiting a family you may want to see what general immunization coverage looks like for the children in the house.  You may also want to know if an older child was immunized if they fall sick.  There is a use case around wanting to check immunizations for children entering into schools but that's really down the road for us and something we can support in multiple ways.
- For child illness, we just show the current state.  We don't keep a history.  We can consider history post MVP.
- Adults - just show the profile for what they are in.  Eg. Pregnant.  For BA we may need to look at what happens if a pregnant women gets malaria.  Do they show up in both registers?  Does the profile show both?  Probalbly the easiest way is to for profile to have one slot to show current information for whatever registers are active.  So in this case, it'll show current state for both pregnancy and malaria.
- We don't show any prior medical history for any other health event.  Eg. Child sickness, pregnancy, Malaria, etc to V1.  Immunization is the one exception.

Other notes:
- For children over 5, we don't allow back entry of immunizations.

In terms of engineering,  we can probably get away with not storing immunization for MVP as most of the kids that will be receiving immunization will only be younger.  So if it adds a lot of engineering and delays we can punt on this to later.  I think the right approach for end product is to show child immunization history basically until the child has an ANC.    At that point knowing vaccine status is not really relevant so we could potentially remove.

**Comment by rowo** [comment]
@mberg Thanks for your determination. 

I've tried to list out the unique profiles configurations below according to the "immunization history disappears at ANC" rule. Profile differences can be as small as what buttons appear or as significant as changing the information/buttons that appear. 

In UI explorations so far, I've explored putting malaria information (which is current and active) into its own row item at the profile top level. See [slides 5 to 10 in client profiles ba](https://docs.google.com/presentation/d/1a5-sLnyzBxIAipec1W4W3R5rr-UaPaAXpAoEVgY2t94/edit#slide=id.g51ca8ef04d_0_0). **Question: For simplicity, we could treat immunization history the same way where it always appears as its own row if it exists. The argument against this is it is not always active information (i.e. during the immunize-able ages). I don't think that's a big deal, but thoughts welcome.**

Adult (male or female) no med info
Adult (male or female) no med info + malaria
Adult (male or female) + immunization history
Adult (male or female) + immunization history + malaria
WRA (woman of repr. age) no med info
WRA + immunization history
WRA + immunization history + malaria
ANC w/ ANC med info/history
ANC w/ ANC med info/history + malaria
PNC w/ PNC med info/history
PNC w/ PNC med info/history + malaria
_WRA + FP info_ `this would only exist if you you can add another FP method for someone with FP already`
WRA + FP info + immunization history
WRA + FP info + immunization history + malaria
Child + immunization info/history
Child + immunization info/history + malaria
Child no immunization history (i.e. late registration but <5)
Child no immunization history + malaria

**Comment by cagulas** [comment]
> Child no immunization history (i.e. late registration but <5)

Right now, the child's medical history is the full history, so it includes immunization, vita A, deworming, MNP, birth certification, etc. Are we talking about removing all of the extra bits and only leaving immunization history when a child transitions to 4/5 yo? I was actually suggesting we leave medical history as it is. It has extra information besides immunizations, but the extra info won't hurt, and removing it seems like adding extra logic, which means extra work. If we do leave medical history for the child as is, then there's no differentiating between child + immunization info and child no immunization info.

**Comment by cagulas** [comment]
Also, I would swap out:

> WRA (woman of repr. age) no med info
WRA + immunization history
WRA + immunization history + malaria
ANC w/ ANC med info/history
ANC w/ ANC med info/history + malaria
PNC w/ PNC med info/history
PNC w/ PNC med info/history + malaria
WRA + FP info this would only exist if you you can add another FP method for someone with FP already
WRA + FP info + immunization history
WRA + FP info + immunization history + malaria

with:
WRA with no med info
WRA with previous child med info
WRA with malaria
WRA with previous child med info + malaria
WRA with FP
WRA with FP + malaria
WRA with FP + malaria + previous child med info
WRA with ANC
WRA with ANC + malaria
WRA with PNC
WRA with PNC + malaria
WRA with PNC + FP
WRA with PNC + FP + malaria

**Comment by rowo** [comment]
@cagulas  I was using immunization as shorthand for all child history, so I guess that works. If a child is registered at 59 months (last possible under 5), what would fields would be available for the CHW to fill out? 

General question about how  the app is built: if an age 4 child is registered and maybe only a few categories will be asked (birth cert, vit A, deworming, etc.), would only those sections show up or would all of them show up, but as empty states?

Ok, I'll update the headings. Though for background, I elected to stop using WRA for ANC/PNC since what shows up for them differs so much from WRA that it was easier to think of ANC and PNC in their own buckets.

**Comment by cagulas** [comment]
> If a child is registered at 59 months (last possible under 5), what fields would be available for the CHW to fill out?

Birth certification, Vitamin A, Deworming, Obs & Illness would all be triggered still.

> if an age 4 child is registered and maybe only a few categories will be asked (birth cert, vit A, deworming, etc.), would only those sections show up in the medical history, or would all of them show up, but as empty states?

Only the sections with service history show up. Immunization section is not shown if no vaccines were given.

> Re: updated profiles. Thanks! I'll update the headings. For background, I elected to stop using WRA for ANC/PNC since what shows up for them differs so much from WRA that it was easier to think of ANC and PNC in their own buckets for designing purposes. But this works okay as well.

Ok cool. I was thinking about it in terms of types of clients (3 types only: adult, child U5, and WRA) and what services they're eligible to be enrolled in.

**Comment by cagulas** [comment]
So that leaves us with: 

Adult - [not anything]
Adult - child med info
Adult - malaria
Adult - child med info + malaria
WRA - [not anything]
WRA - child med info
WRA - malaria
WRA - child med info + malaria
WRA - FP
WRA - FP + child med info
WRA - FP + malaria
WRA - FP + child med info + malaria 
WRA - ANC
WRA - ANC + malaria
WRA - PNC
WRA - PNC + malaria
WRA - PNC + FP
WRA - PNC + FP + malaria
Child - child med info
Child - child med info + malaria

The first 4 rows are sort of the same as the 2nd set of four rows, with the exception that WRA are eligible for FP and ANC services, so they'd have the appropriate FP and ANC registration actions available to them.

**Comment by cagulas** [comment]
If discussion on this issue is finalized, we can close it. I created the new implementation issue for this here: https://github.com/OpenSRP/opensrp-client-chw/issues/297

**Comment by msschroeder** [comment]
@cagulas I think you can close it

**Comment by cagulas** [comment]
@msschroeder I'll close this, thanks. Can you make sure the above final list is added to the BA discussion documentation somewhere?
