### ISSUE TITLE
all 10w and three of the 14w vaccines missing from upcoming services page

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-chw#340]
![Screenshot_20190430-102814](https://user-images.githubusercontent.com/3488986/56947054-ab6c8c80-6b34-11e9-98a3-edd4674cf402.png)

I registered a 10m old child and on the upcoming services page, the 10w vaccine section is missing completely, as well as 3 of the vaccines for 14w: Penta 3, OPV 3, and PCV 3. Right now, only IPV is appearing for 14w.

To replicate, register a new U5 child who is about 10m old and then go to the upcoming services page.

**Comment by mahmud6390** [comment]
I checked the issue. 10 week vaccine is depend on 6week given vaccine like opv1,pcv1.. and 14week vaccines penta 3,opv3,pcv 3 are depend on 10week vaccines penta2,opv2,pcv2 so that these vaccine also not showing as due state. we can not getting this from db.At this stage what will be the upcoming screen for these group?

**Comment by cagulas** [comment]
Ah I see. Since there's logic to this, let's keep it as is for now. We may want to implement some special rule a bit later though, but I'm happy to leave it as is for now though. Thanks.
