### ISSUE TITLE
Editing home visit vaccine data enhancement

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#342]
One unique situation when editing a home visit is when you register an older kid and back-record vaccines. In that home visit, then, you have multiple vaccine dependencies (i.e. 10 weeks need to be filled before 14 weeks, etc.), so in this case, we discussed that if the user happens to edit previous vaccines that may or may not invalidate later vaccines, then we would simply delete the data entries for the later vaccines and make the user fill the later vaccines in again.

**Comment by cagulas** [comment]
After speaking with Ronald, we need to address this as a priority, as it will create data errors.

@rkodev fyi.

**Comment by cagulas** [comment]
QA 28 May:

See screenshot below. I edited the 6w vaccines and marked them as not done, and the 10w vaccines were correctly deleted, but the 14w vaccines were not deleted, when they should be, because they're based on the 10w vaccines.

![Screenshot_20190528-171812](https://user-images.githubusercontent.com/3488986/58485467-c864a180-816c-11e9-9374-08d98b0cb193.png)

**Comment by cafootitt** [comment]
lgtm
