### ISSUE TITLE
Provide specs for standardized logo (unicef + country emblem)

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#349]

**Comment by rowo** [comment]
Is this what is meant by specs?

- ![Untitled-1](https://user-images.githubusercontent.com/1584163/57272645-8e6b1880-7062-11e9-8512-f32632f9900d.png)
- See https://github.com/OpenSRP/opensrp-client-chw/issues/79#issuecomment-459504525 as well.
- I wasn't in the conversations for the app login image originally, but it does seem more like a branding for the app rather than an app icon, so it would traditionally fall under UNICEF's role to provide cobranding guidelines for this.

**Comment by cagulas** [comment]
@rowo There was no "conversation" around the logo that you missed. They sent the two logos over, and I asked how they should be arranged over chat message, and Hawi said side by side. That's all. 

Sorry, I don't get your point about this is more branding than logo?

**Comment by rowo** [comment]
Maybe there should be a conversation. I would probably recommend they send guidelines since this isn't really an app logo — it's more about rules to position logos together next to each other. Most large branding guidelines have specs around how to do this. It might be called a "cobranding lockup" or "cobranding guidelines" in their branding doc. I'm sure Unicef's guidelines has something around this..

**Comment by cagulas** [comment]
Sent the client an email to enquire about this.

**Comment by rowo** [comment]
This is what the guidelines have relevant to this. The partnership one looks like what we did. I think this as detailed as we can get since emblems are all different shapes. 

<img width="1247" alt="Screen Shot 2019-05-31 at 1 02 19 AM" src="https://user-images.githubusercontent.com/1584163/58720479-4957af00-83a0-11e9-89fc-6c45bd987400.png">
<img width="1254" alt="Screen Shot 2019-05-31 at 1 02 27 AM" src="https://user-images.githubusercontent.com/1584163/58720483-4a88dc00-83a0-11e9-9e28-3296f4ea431c.png">
