### ISSUE TITLE
QA Feedback 27th May

### ISSUE THREAD

**Issue by rkodev** [OpenSRP/opensrp-client-chw#366]
Feedback from Leigh on May 27th:

- [ ] 1  Under the family profile view – the colour code that represents services due seems misleading. It looks like it represents the gender of the child, because it is attached to their profile pic. Could the code be moved to the right hand side of that row for clarity?

- [ ] 2   Under record services – I am able to record all immunizations and nutrition interventions as given on the same day, without a warning or prompt to double check dates. This may be warranted because this is usually what happens if someone rushes through data entry. Do you we have a list of the max number of vaccines that can or should be given on a certain day? I know that more than one dose of vitamin A given at the same time can cause Vitamin A toxicity.

- [x] 3    Under child profile page “Not visiting this month” seems to freeze the app. Can you include circling dots or something to indicate that it is processing?

- [x] 4    Check mark for no services due is great! Due only toggle is great!
- [x] 5   When I try and submit a kid form it hangs. Add a spinner to indicate the processing

**Comment by cagulas** [comment]
@rowo Might you be able to weigh in on number 1 above? I think we could potentially show the pink or blue circle around the avatar picture perhaps?

For number 2, I think we should wait to enforce data constraints for now. In Zambia, we faced an issue where the data constraints had to be "relaxed" to allow for the fact that some health workers provide immunizations a bit earlier than the due date. Until we get a better picture of what the possible scenarios are in Liberia, I think it's best to wait before implementing any constraints.

**Comment by rowo** [comment]
1 — I can see where it could be confusing, but I think this it's low priority since it shouldn't be confusing after using the app for a while and the cost to being confused isn't too great if the users can read, which I believe we are assuming given the length and style of data entry.

But, I'm not sure there is any treatment that keeps the "due item" flag as a simple circle icon and makes it not confused with gender even if it's both written and visualized in the avatar. So the I solution I see, if we choose to do so, would be to write it out similar to what we're moving toward in TZ BA and Malawi eregister:

<img width="384" alt="Screen Shot 2019-05-30 at 12 40 49 AM" src="https://user-images.githubusercontent.com/1584163/58608897-a0ac3100-8273-11e9-9e67-c84a12e51b3b.png">

<img width="386" alt="Screen Shot 2019-05-30 at 12 38 47 AM" src="https://user-images.githubusercontent.com/1584163/58608871-86725300-8273-11e9-9539-a2487886787a.png">

**Comment by cagulas** [comment]
@rowo Thanks for your feedback. If ok with you. I'm going to move this to icebox, so we keep a history of the discussion, but I think given the roll-out timeline, we'll have to come back to this later.

**Comment by cafootitt** [comment]
Cleaning up the board and closing this issue, as we won't be addressing remaining feedback.
