### ISSUE TITLE
Implement manual update button in Dashboard

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#377]
The reporting indicators will automatically update after 15 minutes. If the health worker views the dashboard in between automatic updates, the numbers may be different from what they expect. We propose adding a manual update button to the Dashboard page, so that users can automatically refresh the indicators in between automatic attempts, so they can be confident they are viewing the most up-to-date information.

Assigning to @rowo to help with the placement and instructions for button design and @allan-allay to implement afterwards.

**Comment by rowo** [comment]
@cagulas Does this do the same thing as the refresh on the hamburger menu?

**Comment by cagulas** [comment]
@rowo No, this would be a different refresh. This essentially is triggering the reporting indicator engine to re-calculate the indicators. I don't believe it has anything to do with the other refresh which attempts to sync with the server. @allan-allay Please correct me if I'm wrong.

**Comment by allan-allay** [comment]
You're right @cagulas. 
While the refresh which is on the navigation drawer will trigger a Sync with the server, this refresh that'll be on the dashboard will basically trigger the computation of the indicators for the display of fresher values instead of having to wait for the periodic job that does this to run.

**Comment by cagulas** [comment]
Thank you @allan-allay

**Comment by cagulas** [comment]
@rowo Would you be able to provide this before Wednesday this week? Allan will be finishing the last indicator and would pick this up after that as the last thing to implement for this sub-project.

**Comment by rowo** [comment]
We can use the same sync button as on the hamburger menu with the question being left or right and right seems okay.

![JobGuides-Recalc](https://user-images.githubusercontent.com/1584163/58835116-1113d300-8623-11e9-9095-307e6b77b5e7.png)

When syncing, does it clear the view and show the loading spinner again?

**Comment by cagulas** [comment]
@rowo Thanks for this. I'm noting that when the user scrolls, the top bar collapses, thus, it would hide the sync button, but I am thinking this is fine, since they'd just need to scroll to the top again to sync.

I do not know the answer as to whether it clears the view or not. @allan-allay will have to answer that.

![Screenshot_20190604-084334](https://user-images.githubusercontent.com/3488986/58854156-2598af80-86a5-11e9-922c-dd47ac06d4e4.png)

**Comment by cagulas** [comment]
@allan-allay This issue is ready for you to work on now.

**Comment by allan-allay** [comment]
Hello, @cagulas and @rowo. 
The desired implementation (that I'll be going for) is, on click, to trigger the indicators computing job immediately, then clear the dashboard view and load everything once the tallies have been computed

**Comment by cafootitt** [comment]
Looks fine to me. I'm going to create a separate issue to have a spinner and toaster message to confirm the sync.
