### ISSUE TITLE
Implement login page for all 4 countries

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#392]
Togo app name: Communauté Amies des Enfants Suivi en Temps Réel (CFC-RTM - Togo)
Guinea app name: Communauté Amies des Enfants Suivi en Temps Réel (CFC-RTM - Guinée)
Chad app name: Communauté Amies des Enfants Suivi en Temps Réel (CFC-RTM - Tchad)
DRC app name: Communauté Amies des Enfants Suivi en Temps Réel (CFC-RTM - RDC)

App logos for the 4 countries: Get from #391 

Everything else should be the same as the Liberia app, i.e. background color, spacing, etc.

**Comment by mahmud6390** [comment]
![chad_login](https://user-images.githubusercontent.com/2793306/59603024-26602580-912a-11e9-8459-1171c939fe0c.png)
![drc_login](https://user-images.githubusercontent.com/2793306/59603026-26f8bc00-912a-11e9-9be2-2c6ee0b93181.png)
![guine](https://user-images.githubusercontent.com/2793306/59603027-26f8bc00-912a-11e9-9a82-bd3e02e1485b.png)
![togo_login](https://user-images.githubusercontent.com/2793306/59603028-27915280-912a-11e9-80fd-d3d5e7759fbe.png)
@cafootitt these are login screen.

**Comment by cafootitt** [comment]
@rowo is going to take a look.

**Comment by rowo** [comment]
@mahmud6390 Can you make the logos the same size? Using your image order, the first one is largest, second is slightly smaller, then I believe the last two I think are the same small size. Please match the sizing of the first image.

![Untitled-1](https://user-images.githubusercontent.com/1584163/59635559-81d8e600-911f-11e9-9e4f-01d09d787d05.png)

**Comment by mahmud6390** [comment]
@cafootitt i am using the images from #391

**Comment by cafootitt** [comment]
@rowo see Mahmud's comment above.

**Comment by rowo** [comment]
@cafootitt @mahmud6390 The logo files should all be the same width. Do you need them to be the same vertical size as well?

**Comment by mahmud6390** [comment]
@rowo i checked it's showing
 togo image size : 1024x396
 drc : 1024x346
chad : 1024x 334
guinea : 1024x407
need same size for all the image.

**Comment by rowo** [comment]
@mahmud6390 Here are all of the images at 1024px x 372px

If you can please match the size to that first Chad image. The specs you provided are the original file size, but i doubt they are the size the images are rendered at since they don't all match in the screenshots.

![wcaro-loginlogo-congo](https://user-images.githubusercontent.com/1584163/59770065-58ca6980-9275-11e9-9cc0-9dd209014c1f.png)
![wcaro-loginlogo-guinea](https://user-images.githubusercontent.com/1584163/59770066-58ca6980-9275-11e9-8b46-feb08ee2cc12.png)
![wcaro-loginlogo-togo](https://user-images.githubusercontent.com/1584163/59770067-58ca6980-9275-11e9-9b7b-b7b23a138310.png)
![wcaro-loginlogo-chad](https://user-images.githubusercontent.com/1584163/59770068-59630000-9275-11e9-91a2-cf8575a3ee11.png)

**Comment by mahmud6390** [comment]
After implement these 
![chad_login_1](https://user-images.githubusercontent.com/2793306/59837411-fce40b80-936e-11e9-85d5-d52e0b13428d.png)
![drc_login_1](https://user-images.githubusercontent.com/2793306/59837416-01102900-936f-11e9-8d45-720f3c7cb882.png)
![guinea_login_1](https://user-images.githubusercontent.com/2793306/59837422-040b1980-936f-11e9-8e26-d3c231e4728c.png)
![togo_login_1](https://user-images.githubusercontent.com/2793306/59837431-066d7380-936f-11e9-8d91-33d1900132dc.png)
![app_icon](https://user-images.githubusercontent.com/2793306/59837436-08cfcd80-936f-11e9-84c4-7916aa69cc16.png)

**Comment by cafootitt** [comment]
lgtm
