### ISSUE TITLE
Reporting dashboard not showing anything even after an hour

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#452]
![Screenshot_20190630-134836](https://user-images.githubusercontent.com/3488986/60395545-daf04300-9b3d-11e9-8e72-42ff637ef561.png)

This is on the Togo version.

**Comment by allan-allay** [comment]
This is fixed in the issue https://github.com/OpenSRP/opensrp-client-reporting/issues/7 with the PR ->  https://github.com/OpenSRP/opensrp-client-reporting/pull/8, and further work done as part of the issue https://github.com/OpenSRP/opensrp-client-reporting/issues/16 with a PR -> https://github.com/OpenSRP/opensrp-client-reporting/pull/17
Once the above code is merged and tested, the issue can be closed

**Comment by cafootitt** [comment]
@allan-allay Great, thanks for the update.
