### ISSUE TITLE
Add the tutorial videos to the Guidebooks section of Job Aids

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#774]
Questions:

- [ ] What will be the method of getting the videos on the device (Will they be too big in size to download with the apk from the Play Store)?
- [ ] Do we need a mockup for this from Roger, or will the videos just appear in rows by alphabetical order, for example?
- [ ] Would the video file name be used as the video title shown in the app, or do we need to specify the video names?

This is just the discussion issue on the approach. I'll create a separate implementation issue once the approach is decided.

![Screenshot_20190912-105011_CFC-RTM - Togo](https://user-images.githubusercontent.com/3488986/64513155-91b43080-d2f0-11e9-9e06-aabdc2930be3.jpg)

**Comment by cafootitt** [comment]
From Craig: 
1) Someone downloads the videos and puts them in a folder on their computer
2) They transfer that folder to a microSD card
3) The supervisor moves around with the microSD card
4) When they get to a health worker, they insert the microSD card into the slot
5) They open a file manager app in the health worker's phone (may require a special app)
6) They copy the folder from the microSD card into the location on the device
7) They open the OpenSRP app and navigate to the videos page to verify they load
They could alternatively travel around with a laptop and connect to the device thorough USB.

From Sam: its possible to transfer the videos using peer-to-peer, also when downloading its possible to save to sd or public storage to that app reinstall does not erase videos
also I think its better to host the videos in a CDN like a s3 public bucket, instead of setting up custom API's

**Comment by cafootitt** [comment]
@rowo We've concluded on a method to do this, described below, so we have a design need next. We will need a mockup of the Guidebooks tab of the app, with the following details:

- Each video is listed on a separate row, by their name (Example names below)
- If the video is accessible on the device, then there's some click to play indication for that video
- If the video is not accessible on the device, then there's some click to download button

Example names of videos:
- Add a new family
- Enregistrer une nouvelle famille
- Trouver un enfant dans le registre

Method:
- All videos can either be downloaded from an s3 bucket (requires an internet connection), or they can be side-loaded onto the device manually
- Somehow, the app will be able to read the device to know whether the video is available
- If the video is available, the user can click to play
- If the video is not available, the user will have an option to click to download the video (requires internet connection)
- Since the video files can be quite large, the preferred method is to side-load them onto the devices, but the download from the internet can be a back-up method that could work quite well over a wifi connection.

We need to make sure of the following:
- When the app is uninstalled or updated via the Play Store, the videos are not deleted, i.e. the new app version can still read whether the videos are accessible on the device, so that the user will not need to download them (again).

@githengi @rkodev Please add more technical specs to this issue as needed for implementation.

**Comment by rowo** [comment]
@githengi @rkodev In an effort to try to minimize work across OpenSRP projects, would any of the below save effort? 
1) Remove any form of displaying progress (just use a spinner or icon change) 
2) Assuming the app knows a video is available on device or not before anything is tapped, we display videos in two tabs (Store vs. Downloaded — kind of like [Offline Maps](https://github.com/OpenSRP/opensrp-client-reveal/issues/442#issuecomment-533653387)), so the different row types wouldn't have to be mixed together and states are simpler
3) Just use the video name instead a label file or file metadata for the row name

**Comment by rkodev** [comment]
@rowo @cafootitt @githengi @ndegwamartin 
1. I think using a spinner will greatly simplify the task.
2. we have 2 tabs in the Jobs Aids already for CHW app. Will we have a tab below on the guide books or will we add another so we have 3 tabs.
![Screenshot_1569241061](https://user-images.githubusercontent.com/43806892/65424881-4f711000-de15-11e9-9899-b724d2edbf00.png)
3. We can use the video name. But we might have to standardized the naming. Like use snake case for all the videos at the end, we can then replace this on the device, and use a popular video codec  (like .mp4 instead of 3gp)

**Comment by rkodev** [comment]
For this task, this is the summary of what to do
Had discussions on the different benefits and use cases that will best suit current needs. On the server-side particularly. We opted to use an S3 bucket with minimal server changes since these files are not particularly security-sensitive and can be available publicly

A. Server Side
1. [ ] To add server endpoint details in the Gradle config that will be the location of the remotely stored files.
2. [ ] The server will be an S3 bucket. No installation other than Nginx will be used to query the server for new files. (Use a header to check the version of existing files and the name of the existing files).
3. [ ] All files should be stored with names in snake_case.

B. Client-Side (App)
1. [ ] Create a repository object that will store metadata on the video files (File Name, Remote Location, Remote Version, Downloaded, LocalFileName)
2. [ ] Check the disk and server for file changes on a Lazy thread every time the guide books section is loaded. Update the file details on the local repository accordingly (Should cater for files copied via local sharing / SD card copy). 
3. [ ] Enable playing the video via an intent to select any of the locally available videos.
4. [ ] Trigger download manually with download action. (Add function to change snake case to proper case)

**Comment by rowo** [comment]
@rkodev 
Play: https://material.io/resources/icons/?search=play&icon=play_circle_outline&style=outline
Save/download: https://material.io/resources/icons/?search=save&icon=save_alt&style=outline

Also, sounds like since we are creating an object to save metadata anyways, then we don't have to do that snakecase stuff and can just define a file label — which is fine.. that was just an idea to save work.

**Comment by cafootitt** [comment]
@rkodev good work on this issue. I'm creating separate (small fixes) issues instead of keeping this issue open.
