### ISSUE TITLE
Make sure PNC health facility visit task is appearing in Guinea

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#970]
See row 17 in the Guinea tab: https://docs.google.com/spreadsheets/d/1aqecWVn68fy62N7orZTn5cvw-1dCXiqnjpyn0ENR8DM/edit#gid=812781458

**Comment by rkodev** [comment]
@cafootitt This is appearing on the PNC home visit (See below) . I'm testing with the staging server. I will keep this in progress until the issue is resolved. More information on the account that was used to test will assist

![Screenshot_1572608474](https://user-images.githubusercontent.com/43806892/68022550-b8219700-fcb5-11e9-9bf8-2a7b0e46d9f3.png)

**Comment by msschroeder** [comment]
lgtm
